-- ============================================================
-- BFP Site Profiler - Database Recreation Script
-- Database: bfpprofiler
-- Generated by analyzing the full project codebase
-- ============================================================

-- Create the database
CREATE DATABASE IF NOT EXISTS `bfpprofiler`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE `bfpprofiler`;

-- ============================================================
-- 1. USER TABLE
-- Referenced in: login.php, checkingUser.php, addNewUser.php,
--   editUser.php, deleteUser.php, getUserList.php, getUserById.php,
--   getInspector.php
-- ============================================================
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(500) DEFAULT NULL,
  `phone_number` VARCHAR(50) DEFAULT NULL,
  `role` VARCHAR(50) NOT NULL COMMENT 'admin, inspector, owner, Chief, CRO',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT 'active, inactive',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- 2. ESTABLISHMENT TABLE
-- Referenced in: addNewEstablishment.php, updateMyEstablishment.php,
--   getMyEstablishment.php, adminGetEstablishment.php,
--   getAcceptedEstablishments.php, inspectionAssignment.php
-- ============================================================
CREATE TABLE IF NOT EXISTS `establishment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `owner_id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `type` VARCHAR(100) DEFAULT NULL,
  `ownership_type` VARCHAR(100) DEFAULT NULL,
  `address` VARCHAR(500) DEFAULT NULL,
  `registration_no` VARCHAR(100) DEFAULT NULL,
  `tin_number` VARCHAR(50) DEFAULT NULL,
  `contact_number` VARCHAR(50) DEFAULT NULL,
  `contact_email` VARCHAR(255) DEFAULT NULL,
  `x_coordinate` VARCHAR(50) DEFAULT NULL COMMENT 'longitude',
  `y_coordinate` VARCHAR(50) DEFAULT NULL COMMENT 'latitude',
  `status` VARCHAR(20) NOT NULL DEFAULT 'active',
  `last_inspection` DATETIME DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_establishment_owner` (`owner_id`),
  CONSTRAINT `fk_establishment_owner` FOREIGN KEY (`owner_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- 3. INSPECTION TABLE
-- Referenced in: adminAddInspection.php, adminUpdateInspection.php,
--   adminGetInspection.php, scheduleInspection.php,
--   cancelInspection.php, getInspectorAssignments.php,
--   getInspectorDashboardData.php, inspectorDasboard.php,
--   updatePaymentStatus.php, getInspectionHistory.php
--
-- NOTE: The project uses two different inspector patterns:
--   - Admin flow uses a single "inspector" column
--   - Chief/schedule flow uses "inspector1" and "inspector2" columns
--   All three columns are included to support both flows.
-- ============================================================
CREATE TABLE IF NOT EXISTS `inspection` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inspector` INT(11) DEFAULT NULL COMMENT 'Single inspector (admin flow)',
  `inspector1` INT(11) DEFAULT NULL COMMENT 'First inspector (chief/schedule flow)',
  `inspector2` INT(11) DEFAULT NULL COMMENT 'Second inspector (chief/schedule flow)',
  `inspection_type` VARCHAR(100) DEFAULT NULL COMMENT 'e.g. routine',
  `inspection_date` DATETIME DEFAULT NULL,
  `priority_level` VARCHAR(50) DEFAULT NULL COMMENT 'e.g. low, medium, high',
  `notes` TEXT DEFAULT NULL,
  `time_slot` VARCHAR(50) DEFAULT NULL COMMENT 'e.g. full-day, morning, afternoon',
  `status` VARCHAR(50) NOT NULL DEFAULT 'status-pen' COMMENT 'status-pen, pending, scheduled, completed, approved',
  `establishment_id` INT(11) NOT NULL,
  `payment` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 = unpaid, 1 = paid',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_inspection_establishment` (`establishment_id`),
  KEY `fk_inspection_inspector` (`inspector`),
  KEY `fk_inspection_inspector1` (`inspector1`),
  KEY `fk_inspection_inspector2` (`inspector2`),
  CONSTRAINT `fk_inspection_establishment` FOREIGN KEY (`establishment_id`) REFERENCES `establishment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_inspection_inspector` FOREIGN KEY (`inspector`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_inspection_inspector1` FOREIGN KEY (`inspector1`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_inspection_inspector2` FOREIGN KEY (`inspector2`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- 4. REPORTS TABLE
-- Referenced in: submitInspectionReport.php, getInspectionReport.php,
--   getInspectorReports.php, getInspectorDashboardData.php,
--   finalizeReport.php, getInspectionHistory.php
-- ============================================================
CREATE TABLE IF NOT EXISTS `reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inspection_id` INT(11) NOT NULL,
  `inspection_order_number` VARCHAR(100) DEFAULT NULL,
  `compliance_status` VARCHAR(50) DEFAULT NULL COMMENT 'compliant, partially_compliant, non_compliant',
  `inspector_notes` TEXT DEFAULT NULL,
  `finalized_at` DATETIME DEFAULT NULL,
  `endorsement_status` VARCHAR(20) DEFAULT 'pending' COMMENT 'pending, endorsed, rejected',
  `endorsement_notes` TEXT DEFAULT NULL,
  `endorsed_by` INT(11) DEFAULT NULL COMMENT 'FK to user (Chief)',
  `endorsed_at` DATETIME DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_reports_inspection` (`inspection_id`),
  KEY `fk_reports_endorsed_by` (`endorsed_by`),
  CONSTRAINT `fk_reports_inspection` FOREIGN KEY (`inspection_id`) REFERENCES `inspection` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_reports_endorsed_by` FOREIGN KEY (`endorsed_by`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- 5. DEFECTS TABLE
-- Referenced in: submitInspectionReport.php, getInspectionReport.php,
--   getInspectorReports.php, updateDefectStatus.php,
--   getInspectorDashboardData.php, getInspectionHistory.php
-- ============================================================
CREATE TABLE IF NOT EXISTS `defects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `defects_details` TEXT NOT NULL,
  `grace_period` VARCHAR(50) DEFAULT NULL COMMENT 'Date string for grace period deadline',
  `report_id` INT(11) NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending, solved',
  `evidence_path` VARCHAR(500) DEFAULT NULL COMMENT 'Relative path to uploaded evidence file',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_defects_report` (`report_id`),
  CONSTRAINT `fk_defects_report` FOREIGN KEY (`report_id`) REFERENCES `reports` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- 6. ACTIVITY_LOG TABLE
-- Referenced in: ActivityLogger.php, getAllActivityLogs.php,
--   getActivityStatistics.php, updatePaymentStatus.php
-- ============================================================
CREATE TABLE IF NOT EXISTS `activity_log` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) DEFAULT NULL,
  `action` VARCHAR(255) DEFAULT NULL COMMENT 'Specific action name e.g. user_login, create_inspection',
  `action_type` VARCHAR(50) DEFAULT NULL COMMENT 'create, update, delete, view, login, logout',
  `module` VARCHAR(100) DEFAULT NULL COMMENT 'inspection, report, defect, establishment, user, authentication, payment, certificates',
  `description` TEXT DEFAULT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `user_agent` TEXT DEFAULT NULL,
  `old_values` JSON DEFAULT NULL COMMENT 'Previous values (for updates)',
  `new_values` JSON DEFAULT NULL COMMENT 'New values',
  `status` VARCHAR(20) NOT NULL DEFAULT 'success' COMMENT 'success, failed, error',
  `error_message` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_activity_log_user` (`user_id`),
  KEY `idx_activity_created_at` (`created_at`),
  KEY `idx_activity_action_type` (`action_type`),
  KEY `idx_activity_module` (`module`),
  CONSTRAINT `fk_activity_log_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- 7. DOCUMENTS TABLE
-- Referenced in: uploadDocument.php
-- Purpose: Store owner-submitted documents (business permits, fire safety certs, etc.)
-- ============================================================
CREATE TABLE IF NOT EXISTS `documents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `establishment_id` INT(11) NOT NULL,
  `owner_id` INT(11) NOT NULL,
  `document_type` VARCHAR(100) NOT NULL COMMENT 'e.g. Business Permit, Fire Safety Inspection Certificate',
  `filename` VARCHAR(255) NOT NULL COMMENT 'Server filename',
  `original_name` VARCHAR(255) NOT NULL COMMENT 'Original filename',
  `file_size` INT(11) DEFAULT NULL COMMENT 'File size in bytes',
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending, approved, rejected',
  `review_notes` TEXT DEFAULT NULL COMMENT 'CRO reviewer notes',
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_documents_establishment` (`establishment_id`),
  KEY `fk_documents_owner` (`owner_id`),
  KEY `idx_documents_status` (`status`),
  CONSTRAINT `fk_documents_establishment` FOREIGN KEY (`establishment_id`) REFERENCES `establishment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_documents_owner` FOREIGN KEY (`owner_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- 8. CERTIFICATES TABLE
-- Referenced in: authorizeCertificate.php, authorizeCertificate.php.bak,
--   authorizeCertificate.php (admin role)
-- ============================================================
CREATE TABLE IF NOT EXISTS `certificates` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `inspection_id` INT(11) NOT NULL,
  `establishment_id` INT(11) NOT NULL,
  `status` VARCHAR(20) NOT NULL COMMENT 'authorized, denied',
  `authorized_by` INT(11) NOT NULL,
  `authorized_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `remarks` TEXT DEFAULT NULL,
  `certificate_number` VARCHAR(50) DEFAULT NULL COMMENT 'e.g. BFP-FSIC-2025-000001',
  PRIMARY KEY (`id`),
  KEY `fk_certificates_inspection` (`inspection_id`),
  KEY `fk_certificates_establishment` (`establishment_id`),
  KEY `fk_certificates_authorized_by` (`authorized_by`),
  CONSTRAINT `fk_certificates_inspection` FOREIGN KEY (`inspection_id`) REFERENCES `inspection` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_certificates_establishment` FOREIGN KEY (`establishment_id`) REFERENCES `establishment` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_certificates_authorized_by` FOREIGN KEY (`authorized_by`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================================
-- SEED: Default admin user (password: admin)
-- Change the password after first login!
-- ============================================================
INSERT INTO `user` (`fullname`, `username`, `email`, `password`, `address`, `phone_number`, `role`, `status`)
VALUES ('System Administrator', 'admin', 'admin@bfp.gov.ph', 'admin', 'BFP Headquarters', '09000000000', 'admin', 'active');
